@extends('layoutDashboard')

@section('content')
    <div class="container-fluid h-screen w-screen py-4 flex items-stretch">
        <div class="w-full">
            <div class="card z-index-2 h-full w-full">
                <div class="card-header pb-0">
                    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                        {{ __('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo integer malesuada nunc vel risus commodo. Elementum eu facilisis sed odio morbi quis commodo odio. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sit amet consectetur adipiscing elit ut aliquam purus. Sed risus ultricies tristique nulla aliquet enim. Quisque non tellus orci ac. Ornare aenean euismod elementum nisi quis eleifend. Vulputate eu scelerisque felis imperdiet proin fermentum. Tristique risus nec feugiat in. Lobortis feugiat vivamus at augue eget arcu. Amet mattis vulputate enim nulla. In ante metus dictum at tempor. Morbi tristique senectus et netus et malesuada fames ac. Sem viverra aliquet eget sit amet tellus cras. Malesuada nunc vel risus commodo viverra. Sagittis orci a scelerisque purus semper eget. Velit egestas dui id ornare arcu odio ut sem nulla.

Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Sed vulputate mi sit amet. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Pretium aenean pharetra magna ac placerat vestibulum lectus. Orci a scelerisque purus semper eget duis. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Egestas congue quisque egestas diam. Ullamcorper morbi tincidunt ornare massa eget. Sagittis aliquam malesuada bibendum arcu vitae elementum. Ultricies mi eget mauris pharetra et ultrices. Ut diam quam nulla porttitor massa id neque. Quisque sagittis purus sit amet volutpat consequat. Sit amet consectetur adipiscing elit.

Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Commodo quis imperdiet massa tincidunt nunc. Magna sit amet purus gravida quis. Mi quis hendrerit dolor magna eget est. Rhoncus urna neque viverra justo. Orci ac auctor augue mauris augue neque gravida in fermentum. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Neque convallis a cras semper auctor. Morbi tristique senectus et netus et malesuada. Sollicitudin tempor id eu nisl nunc.

Sed libero enim sed faucibus turpis in eu. Augue ut lectus arcu bibendum at varius. Gravida neque convallis a cras semper auctor neque. Pretium nibh ipsum consequat nisl vel pretium. Netus et malesuada fames ac. Ultricies lacus sed turpis tincidunt id. Sed cras ornare arcu dui vivamus. Euismod in pellentesque massa placerat duis ultricies lacus sed. Tristique senectus et netus et malesuada. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Condimentum lacinia quis vel eros. Enim sed faucibus turpis in eu. Tristique senectus et netus et malesuada fames ac. In nisl nisi scelerisque eu ultrices vitae. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Risus viverra adipiscing at in tellus integer. Ornare massa eget egestas purus.

Gravida rutrum quisque non tellus orci ac auctor. Vitae congue mauris rhoncus aenean vel. Vel facilisis volutpat est velit egestas dui id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Vitae tempus quam pellentesque nec nam aliquam sem. Dui vivamus arcu felis bibendum ut tristique et egestas. Aliquam purus sit amet luctus venenatis lectus magna fringilla urna. Risus at ultrices mi tempus imperdiet nulla. Commodo viverra maecenas accumsan lacus. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat.

Sem nulla pharetra diam sit amet nisl suscipit. Condimentum lacinia quis vel eros donec ac odio tempor. Ornare massa eget egestas purus viverra accumsan in nisl. Sed velit dignissim sodales ut eu sem integer vitae justo. Dui id ornare arcu odio ut sem nulla pharetra diam. Proin fermentum leo vel orci porta non pulvinar. Tellus id interdum velit laoreet id donec ultrices. Leo duis ut diam quam nulla porttitor. Volutpat est velit egestas dui id ornare arcu odio ut. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. In vitae turpis massa sed elementum tempus egestas. Scelerisque felis imperdiet proin fermentum. Arcu cursus euismod quis viverra nibh cras pulvinar. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Et netus et malesuada fames ac. Suscipit adipiscing bibendum est ultricies. Netus et malesuada fames ac turpis.

Felis eget velit aliquet sagittis id consectetur. Eu consequat ac felis donec. Non sodales neque sodales ut etiam sit amet. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Sit amet tellus cras adipiscing enim eu turpis. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Nisl tincidunt eget nullam non nisi est. Sed risus pretium quam vulputate dignissim suspendisse. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Metus aliquam eleifend mi in. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Dui faucibus in ornare quam. Fermentum odio eu feugiat pretium nibh ipsum consequat.

Hendrerit dolor magna eget est lorem ipsum. Lorem dolor sed viverra ipsum nunc aliquet. Id diam vel quam elementum pulvinar etiam. Condimentum vitae sapien pellentesque habitant morbi. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Nulla aliquet enim tortor at auctor urna nunc. Sed viverra ipsum nunc aliquet. Feugiat pretium nibh ipsum consequat nisl vel. Aliquet lectus proin nibh nisl condimentum id venenatis. Tempus quam pellentesque nec nam aliquam. Risus ultricies tristique nulla aliquet enim tortor at auctor. Ut porttitor leo a diam sollicitudin.

Adipiscing elit ut aliquam purus sit. Eget mauris pharetra et ultrices neque ornare. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Elit at imperdiet dui accumsan sit amet nulla. Adipiscing at in tellus integer feugiat scelerisque. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. At volutpat diam ut venenatis tellus in. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Faucibus pulvinar elementum integer enim neque volutpat ac. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Bibendum enim facilisis gravida neque convallis a cras. Sed arcu non odio euismod. Et leo duis ut diam quam. Amet luctus venenatis lectus magna fringilla urna. Enim sit amet venenatis urna cursus. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Imperdiet sed euismod nisi porta lorem. Diam maecenas sed enim ut sem.

Nibh nisl condimentum id venenatis a condimentum vitae. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Ultricies mi eget mauris pharetra et ultrices neque. Varius quam quisque id diam. Mattis pellentesque id nibh tortor id aliquet lectus proin. Nisi scelerisque eu ultrices vitae auctor eu augue. Euismod lacinia at quis risus sed vulputate odio ut enim. Augue neque gravida in fermentum. Imperdiet nulla malesuada pellentesque elit eget gravida. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Habitant morbi tristique senectus et netus et malesuada. In hac habitasse platea dictumst vestibulum rhoncus est. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc sed blandit libero volutpat sed. Massa placerat duis ultricies lacus sed turpis tincidunt id. Proin sed libero enim sed faucibus turpis in eu mi.') }}
                    </h2>
                </div>
            </div>
        </div>
    </div>
@endsection 